# ~/.xinitrc

# Set QT to respect GTK theme
export QT_QPA_PLATFORMTHEME=gtk2

# Desktop Environment startx options
#exec gnome-session  # Start Gnome 3
#exec startkde       # Start KDE 5
#exec mate-session   # Start Mate
#exec startxfce4     # Start Xfce4
#exec startlxde      # Start LXDE

# Window Manager startx options
#exec i3             # Start i3
#exec awesome        # Start Awesome
#exec openbox        # Start Openbox
#exec dwm            # Start DWM
